version: '3.7'
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=no

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: directorydb
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  people-service:
    build: ./directory-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka

  report-service:
    build: ./report-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - kafka

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - directory-service
      - report-service
